(() => {
  "use strict";
  const ROUND_COUNT = 5, ROUND_SECONDS = 60, MAX_ROUND_SCORE = 5000;
  const STORAGE_KEY = "gamestreet:scores:v1", NAME_KEY = "gamestreet:player:v1";
  const LOCATIONS = [
    {id:"trafalgar-london",city:"London",country:"United Kingdom",lat:51.508165,lng:-0.128143,file:"Trafalgar Square 360 Panorama, London - Jun 2009.jpg",author:"David Iliff",license:"CC BY-SA 3.0",hint:"Một quảng trường lớn ở trung tâm London, nổi tiếng với các tượng sư tử và cột Nelson."},
    {id:"times-square-nyc",city:"New York",country:"United States",lat:40.757117,lng:-73.985936,file:"20080910 Times Square, New York panorama.JPG",author:"Fod",license:"CC BY 2.5 DK",hint:"Một giao lộ sáng đèn ở Manhattan, nơi Broadway cắt qua lưới đường phố New York."},
    {id:"washingtonplatz-berlin",city:"Berlin",country:"Germany",lat:52.523868,lng:13.370178,file:"Berlin Washington Platz – 360° Panorama.jpg",author:"Maximilian Schönherr",license:"CC BY-SA 4.0",hint:"Quảng trường ngay phía nam nhà ga trung tâm Berlin, bên bờ sông Spree."},
    {id:"piazza-navona-rome",city:"Rome",country:"Italy",lat:41.899453,lng:12.473075,file:"Piazza Navona 360 panoramic view.jpg",author:"MatthiasKabel",license:"CC BY-SA 3.0",hint:"Một quảng trường Baroque của Rome nằm trên dấu tích sân vận động cổ Domitian."},
    {id:"sydney-tower",city:"Sydney",country:"Australia",lat:-33.870456,lng:151.208889,file:"Sydney Tower Panorama.jpg",author:"Gauthier Pelloquin",license:"CC BY-SA 3.0",hint:"Panorama chụp từ một đài quan sát cao giữa khu thương mại trung tâm Sydney."},
    {id:"louvre-paris",city:"Paris",country:"France",lat:48.861689,lng:2.333418,file:"Louvre panosphere 20200303.jpg",author:"Daniel Kraft",license:"CC BY-SA 3.0",hint:"Sân Napoléon của một bảo tàng nổi tiếng, gần sông Seine ở Paris."}
  ];
  const $ = id => document.getElementById(id);
  const screens = ["homeScreen","gameScreen","resultScreen","summaryScreen"];
  const state = {player:"Explorer",round:0,totalScore:0,rounds:[],selectedLocations:[],guess:null,timer:ROUND_SECONDS,timerId:null,guessMap:null,guessMarker:null,resultMap:null,resultLayers:[],panoOffset:50,dragging:false,dragStartX:0,dragStartOffset:50,submitting:false};
  const commonsFileUrl = (file,width=4096) => `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=${width}`;
  const commonsPageUrl = file => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file).replace(/%20/g,"_")}`;
  function showScreen(id){ screens.forEach(s => $(s).classList.toggle("hidden",s!==id)); window.scrollTo({top:0,behavior:"instant"}); }
  function shuffle(array){ const copy=[...array]; for(let i=copy.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [copy[i],copy[j]]=[copy[j],copy[i]]; } return copy; }
  function sanitizeName(raw){ const clean=raw.replace(/[<>]/g,"").replace(/\s+/g," ").trim(); return clean.slice(0,20)||"Explorer"; }
  function haversineMeters(a,b){ const R=6371000,toRad=d=>d*Math.PI/180,dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng),lat1=toRad(a.lat),lat2=toRad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2; return 2*R*Math.asin(Math.min(1,Math.sqrt(h))); }
  function scoreForDistance(distanceM){ if(!Number.isFinite(distanceM))return 0; if(distanceM<=50)return MAX_ROUND_SCORE; return Math.max(0,Math.min(MAX_ROUND_SCORE,Math.round(MAX_ROUND_SCORE*Math.exp(-distanceM/2000)))); }
  function formatDistance(meters){ if(!Number.isFinite(meters))return "—"; if(meters<1000)return `${Math.round(meters)} m`; if(meters<100000)return `${(meters/1000).toFixed(1)} km`; return `${Math.round(meters/1000).toLocaleString("vi-VN")} km`; }
  function toast(message){ const node=$("toast"); node.textContent=message; node.classList.add("show"); clearTimeout(node._timer); node._timer=setTimeout(()=>node.classList.remove("show"),2200); }
  function makePinIcon(className=""){ return L.divIcon({className:"",html:`<div class="custom-pin ${className}"></div>`,iconSize:[28,28],iconAnchor:[8,25]}); }
  function initGuessMap(){ if(state.guessMap)return; state.guessMap=L.map("guessMap",{zoomControl:true,minZoom:1,worldCopyJump:true,attributionControl:true}).setView([20,5],1); L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.guessMap); state.guessMap.on("click",e=>setGuess(e.latlng)); }
  function initResultMap(){ if(state.resultMap)return; state.resultMap=L.map("resultMap",{zoomControl:true,minZoom:1,worldCopyJump:true}); L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(state.resultMap); }
  function setGuess(latlng){ state.guess={lat:latlng.lat,lng:latlng.lng}; if(state.guessMarker)state.guessMarker.setLatLng(latlng); else state.guessMarker=L.marker(latlng,{icon:makePinIcon()}).addTo(state.guessMap); const button=$("submitGuessBtn"); button.disabled=false; button.textContent="GỬI DỰ ĐOÁN"; }
  function resetGuessMap(){ state.guess=null; if(state.guessMarker){state.guessMap.removeLayer(state.guessMarker);state.guessMarker=null;} state.guessMap.setView([20,5],1,{animate:false}); $("submitGuessBtn").disabled=true; $("submitGuessBtn").textContent="CHỌN MỘT VỊ TRÍ"; }
  function startGame(){ state.player=sanitizeName($("playerName").value); localStorage.setItem(NAME_KEY,state.player); state.round=0; state.totalScore=0; state.rounds=[]; state.selectedLocations=shuffle(LOCATIONS).slice(0,ROUND_COUNT); showScreen("gameScreen"); initGuessMap(); setTimeout(()=>{state.guessMap.invalidateSize();beginRound();},60); }
  function beginRound(){ state.submitting=false; resetGuessMap(); $("guessPanel").classList.remove("expanded"); $("roundLabel").textContent=`${state.round+1} / ${ROUND_COUNT}`; $("scoreLabel").textContent=state.totalScore.toLocaleString("vi-VN"); const location=state.selectedLocations[state.round],track=$("panoramaTrack"); track.style.opacity=".2"; state.panoOffset=15+Math.random()*70; track.style.backgroundPosition=`${state.panoOffset}% center`; track.style.backgroundImage=`url("${commonsFileUrl(location.file)}")`; const preload=new Image(); preload.onload=()=>{track.style.opacity="1";}; preload.onerror=()=>{track.style.opacity=".7";toast("Không tải được panorama chất lượng cao. Hãy kiểm tra mạng.");}; preload.src=commonsFileUrl(location.file); const credit=$("panoCredit"); credit.href=commonsPageUrl(location.file); credit.textContent=`${location.author} · ${location.license} · Wikimedia Commons`; startTimer(); }
  function startTimer(){ clearInterval(state.timerId); state.timer=ROUND_SECONDS; updateTimerUi(); state.timerId=setInterval(()=>{state.timer-=1;updateTimerUi();if(state.timer<=0){clearInterval(state.timerId);if(state.guess)submitGuess(true);else{toast("Hết giờ — vòng này 0 điểm.");submitNoGuess();}}},1000); }
  function updateTimerUi(){ $("timerLabel").textContent=String(Math.max(0,state.timer)); $("timerPill").classList.toggle("warning",state.timer<=10); }
  function submitNoGuess(){ if(state.submitting)return; state.submitting=true; clearInterval(state.timerId); const location=state.selectedLocations[state.round],result={location,guess:null,distance:Infinity,score:0}; state.rounds.push(result); showRoundResult(result); }
  function submitGuess(auto=false){ if(state.submitting||!state.guess)return; state.submitting=true; clearInterval(state.timerId); const location=state.selectedLocations[state.round],actual={lat:location.lat,lng:location.lng},distance=haversineMeters(state.guess,actual),score=scoreForDistance(distance),result={location,guess:{...state.guess},distance,score}; state.rounds.push(result); state.totalScore+=score; if(auto)toast("Hết giờ — đã tự gửi ghim cuối cùng."); showRoundResult(result); }
  function showRoundResult(result){ showScreen("resultScreen"); initResultMap(); setTimeout(()=>{state.resultMap.invalidateSize(); state.resultLayers.forEach(layer=>state.resultMap.removeLayer(layer)); state.resultLayers=[]; const actual=L.latLng(result.location.lat,result.location.lng),actualMarker=L.marker(actual,{icon:makePinIcon("actual-pin")}).addTo(state.resultMap); state.resultLayers.push(actualMarker); if(result.guess){const guess=L.latLng(result.guess.lat,result.guess.lng),guessMarker=L.marker(guess,{icon:makePinIcon()}).addTo(state.resultMap),line=L.polyline([guess,actual],{color:"#f97316",weight:3,opacity:.8,dashArray:"7 7"}).addTo(state.resultMap); state.resultLayers.push(guessMarker,line); state.resultMap.fitBounds(L.latLngBounds([guess,actual]).pad(.4),{maxZoom:13});}else state.resultMap.setView(actual,10);},70); $("resultRoundMeta").textContent=`KẾT QUẢ VÒNG ${state.round+1} / ${ROUND_COUNT}`; $("distanceBig").textContent=formatDistance(result.distance); $("roundScoreBig").textContent=`+${result.score.toLocaleString("vi-VN")}`; $("resultHeadline").textContent=result.guess?resultMessage(result.distance):"Bạn chưa đặt ghim trước khi hết giờ."; $("roundFact").innerHTML=`<strong>${result.location.city}, ${result.location.country}</strong><br>${result.location.hint}<br><span>Ảnh: ${result.location.author} · ${result.location.license}</span>`; $("nextRoundBtn").innerHTML=state.round===ROUND_COUNT-1?"XEM TỔNG KẾT <span>→</span>":"VÒNG TIẾP THEO <span>→</span>"; }
  function resultMessage(distance){ if(distance<=50)return "Gần như chính xác tuyệt đối. Một cú ghim xuất sắc!"; if(distance<=500)return "Rất sát vị trí thật — bạn đọc địa hình và dấu hiệu rất tốt."; if(distance<=5000)return "Đúng khu vực. Chỉ còn thiếu một chút độ chính xác."; if(distance<=50000)return "Bạn đã tìm đúng vùng lân cận, nhưng vẫn còn một khoảng cách đáng kể."; return "Một cú đoán táo bạo. Vòng tiếp theo vẫn còn nhiều điểm để gỡ lại."; }
  function nextRound(){ state.round+=1; if(state.round>=ROUND_COUNT)finishGame(); else{showScreen("gameScreen");setTimeout(()=>{state.guessMap.invalidateSize();beginRound();},50);} }
  function getScores(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");}catch{return [];} }
  function saveScore(entry){ const scores=getScores(); scores.push(entry); scores.sort((a,b)=>b.score-a.score||a.avgDistance-b.avgDistance); localStorage.setItem(STORAGE_KEY,JSON.stringify(scores.slice(0,30))); return scores; }
  function finishGame(){ const finiteDistances=state.rounds.filter(r=>Number.isFinite(r.distance)).map(r=>r.distance),avgDistance=finiteDistances.length?finiteDistances.reduce((a,b)=>a+b,0)/finiteDistances.length:Infinity,previous=getScores(),previousBest=previous.filter(x=>x.player===state.player).reduce((best,x)=>Math.max(best,x.score),0),entry={player:state.player,score:state.totalScore,avgDistance,date:new Date().toISOString()},allScores=saveScore(entry),rank=allScores.findIndex(x=>x.date===entry.date&&x.player===entry.player)+1,personalBest=Math.max(previousBest,state.totalScore); $("summaryTitle").textContent=state.totalScore>=18000?"Bản năng địa lý tuyệt vời!":state.totalScore>=10000?"Một chuyến đi rất khá!":"Thế giới còn nhiều điều để đoán!"; $("summarySub").textContent=`${state.player}, bạn đã hoàn thành 5 địa điểm vòng quanh thế giới.`; $("finalScore").textContent=state.totalScore.toLocaleString("vi-VN"); $("avgDistance").textContent=formatDistance(avgDistance); $("personalBest").textContent=personalBest.toLocaleString("vi-VN"); $("localRank").textContent=rank>0?`#${rank}`:"—"; $("roundBreakdown").innerHTML=state.rounds.map((r,i)=>`<div class="round-chip"><span>V${i+1}</span><strong>${r.score.toLocaleString("vi-VN")}</strong></div>`).join(""); showScreen("summaryScreen"); renderLeaderboard(); }
  function renderLeaderboard(){ const scores=getScores().slice(0,5),list=$("leaderboardList"); if(!scores.length){list.innerHTML=`<div class="empty-leaderboard">Chưa có điểm. Hãy trở thành người đầu tiên đặt kỷ lục trên thiết bị này.</div>`;return;} list.innerHTML=scores.map((entry,index)=>{const date=new Date(entry.date),when=Number.isNaN(date.getTime())?"":date.toLocaleDateString("vi-VN");return `<div class="score-row"><span class="score-rank">#${index+1}</span><div><span class="score-name">${escapeHtml(entry.player)}</span><span class="score-meta">${when} · TB ${formatDistance(entry.avgDistance)}</span></div><span class="score-points">${Number(entry.score).toLocaleString("vi-VN")}</span></div>`;}).join(""); }
  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));}
  function quitGame(){ if(!window.confirm("Thoát ván hiện tại? Tiến trình của ván này sẽ không được lưu."))return; clearInterval(state.timerId); showScreen("homeScreen"); }
  async function shareResult(){ const text=`Tôi vừa đạt ${state.totalScore.toLocaleString("vi-VN")}/25.000 điểm trên GameStreet 🌍 Bạn đoán được bao nhiêu?`; try{if(navigator.share)await navigator.share({title:"GameStreet",text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);toast("Đã sao chép kết quả vào clipboard.");}}catch(err){if(err?.name!=="AbortError")toast("Không thể chia sẻ lúc này.");} }
  function installPanoramaDrag(){ const viewport=$("panoramaViewport"),track=$("panoramaTrack"),getX=e=>e.touches?e.touches[0].clientX:e.clientX,down=e=>{state.dragging=true;state.dragStartX=getX(e);state.dragStartOffset=state.panoOffset;viewport.classList.add("dragging");},move=e=>{if(!state.dragging)return;const delta=getX(e)-state.dragStartX;state.panoOffset=state.dragStartOffset+(delta/Math.max(320,viewport.clientWidth))*45;track.style.backgroundPosition=`${state.panoOffset}% center`;},up=()=>{state.dragging=false;viewport.classList.remove("dragging");}; viewport.addEventListener("mousedown",down);window.addEventListener("mousemove",move);window.addEventListener("mouseup",up);viewport.addEventListener("touchstart",down,{passive:true});viewport.addEventListener("touchmove",move,{passive:true});viewport.addEventListener("touchend",up,{passive:true}); }
  function bindUi(){ $("startBtn").addEventListener("click",startGame); $("playerName").addEventListener("keydown",e=>{if(e.key==="Enter")startGame();}); $("submitGuessBtn").addEventListener("click",()=>submitGuess(false)); $("nextRoundBtn").addEventListener("click",nextRound); $("playAgainBtn").addEventListener("click",startGame); $("backHomeBtn").addEventListener("click",()=>showScreen("homeScreen")); $("quitBtn").addEventListener("click",quitGame); $("shareBtn").addEventListener("click",shareResult); $("expandMapBtn").addEventListener("click",()=>{$("guessPanel").classList.toggle("expanded");setTimeout(()=>state.guessMap?.invalidateSize(),240);}); $("howBtn").addEventListener("click",()=>$("howDialog").showModal()); $("closeHowBtn").addEventListener("click",()=>$("howDialog").close()); $("clearScoresBtn").addEventListener("click",()=>{if(!window.confirm("Xóa toàn bộ bảng điểm cục bộ trên thiết bị này?"))return;localStorage.removeItem(STORAGE_KEY);renderLeaderboard();toast("Đã xóa bảng điểm cục bộ.");}); window.addEventListener("resize",()=>{state.guessMap?.invalidateSize();state.resultMap?.invalidateSize();}); }
  function bootstrap(){ $("playerName").value=localStorage.getItem(NAME_KEY)||""; renderLeaderboard(); bindUi(); installPanoramaDrag(); }
  document.addEventListener("DOMContentLoaded",bootstrap);
})();
